### ISSUE TITLE
Newbie here need some clarification on the resistance values 

### ISSUE THREAD

**Issue by Suresh3012** [abzman/esp-stuff#1]
Newbie here !
This is my first post and I'm not sure if this is the right place.
I would like to know the values of resistance you have used in  the project for ESP- FLOW (yf s201 water flow meter) .
Thanks In Advance

**Comment by abzman** [comment]
I used 12k and 22k resistors.  This change is being reflected on my blog
entry.

**Comment by Suresh3012** [comment]
Thanks
